# Generated by Django 3.2.6 on 2021-08-21 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='sex',
            new_name='prefix',
        ),
    ]
