# Generated by Django 3.2.6 on 2021-08-27 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_rename_sex_author_prefix'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
