# Generated by Django 3.2.6 on 2021-09-03 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_category_student_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='subject_en',
            new_name='subject_name_en',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='subject_name',
            new_name='subject_name_th',
        ),
    ]
