# Generated by Django 3.2.6 on 2021-09-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20210903_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='student',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='web.Student'),
        ),
    ]
